services:
  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    container_name: ollama_server
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./.ollama-models:/root/.ollama
    # Descomenta el siguiente bloque si tienes una tarjeta gráfica NVIDIA y
    # el nvidia-container-toolkit instalado en tu sistema, para acelerar Ollama.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

